### ISSUE TITLE
.net 8

### ISSUE THREAD

**Issue by ekjuanrejon** [pengweiqhca/Xunit.DependencyInjection#117]
this doen't seem to work with .net 8 and latest xunit packages

**Comment by pengweiqhca** [comment]
Has any issue?

**Comment by ekjuanrejon** [comment]
An exception occurred while invoking executor 'executor://xunit/VsTestRunner2/netcoreapp': Method 'LogRaw' in type 'Xunit.Runner.VisualStudio.VisualStudioRunnerLogger' from assembly 'xunit.runner.visualstudio.dotnetcore.testadapter, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' does not have an implementation.
Stack trace:
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTests(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, Func`1 getRunInfos)
   at Xunit.Runner.VisualStudio.VsTestRunner.Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 202
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.Common/ExtensionDecorators/SerialTestRunDecorator.cs:line 44
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithTests.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUri, RunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/RunTestsWithTests.cs:line 72
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs:line 466

**Comment by pengweiqhca** [comment]
Maybe you should upgrade `xunit` and `xunit.runner.visualstudio`, and use the same version.

**Comment by WeihanLi** [comment]
looks good to me, I'm using `net8.0` and with the packages

``` xml
    <PackageVersion Include="xunit" Version="2.7.0" />
    <PackageVersion Include="Xunit.DependencyInjection" Version="9.0.1" />
    <PackageVersion Include="Xunit.DependencyInjection.AspNetCoreTesting" Version="9.0.0" />
    <PackageVersion Include="Xunit.DependencyInjection.Logging" Version="9.0.0" />    
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.7" />
```

https://github.com/WeihanLi/XunitDependencyInjection.Samples/blob/main/Directory.Packages.props
