### ISSUE TITLE
Implement IAsyncDisposable in HostManager

### ISSUE THREAD

**Issue by Thomas-X** [pengweiqhca/Xunit.DependencyInjection#60]
**Describe the bug**
It seems that HostManager only calls .Dispose and doesn't implement .DisposeAsync for types that only implement that interface.

**Stacktrace**
```
[xUnit.net 00:00:35.71] Integration.Tests: Catastrophic failure: System.InvalidOperationException: 'Microsoft.Playwright.Core.Browser' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
   at Xunit.DependencyInjection.HostManager.Dispose()
   at Xunit.Sdk.DisposalTracker.Dispose() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\DisposalTracker.cs:line 26
   at Xunit.Sdk.TestFrameworkExecutor`1.Dispose() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkExecutor.cs:line 72
   at DisposableExtensions.SafeDispose(IDisposable disposable) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Extensions\DisposableExtensions.cs:line 8
   at Xunit.Xunit2.Dispose() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 86
   at Xunit.XunitFrontController.Dispose() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 155
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in /_/src/xunit.runner.visualstudio/VsTestRunner.cs:line 620
```

**Possible cause**

```csharp
// The issue (I think) https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/51c86a5288f045e4f01fd1f5a6328be7fe73f7fe/Xunit.DependencyInjection/HostManager.cs#L122
        public void Dispose()
        {
            for (var index = _hosts.Count - 1; index >= 0; index--)
                _hosts[index].Dispose();
        }

// Should be something like

        public void Dispose()
        {
            for (var index = _hosts.Count - 1; index >= 0; index--)
                try {
                    _hosts[index].Dispose();
                } catch (InvalidOperationException) when (e.Message.Contains("IAsyncDisposable")) {
                    _hosts[index].DisposeAsync().GetAwaiter().GetResult();
                } catch (Exception e) {
                   throw e;
                }
        }
```

**To Reproduce**
1. add an implementation with only IAsyncDisposable to the IoC
2. watch it blow up

**Expected behavior**
That services with IAsyncDisposable only are also properly disposed in the IoC

Let me know if I can be of help and I'll make a PR for this, or if I'm completely on the wrong path @pengweiqhca :)

**Comment by pengweiqhca** [comment]
[Completed](https://github.com/pengweiqhca/Xunit.DependencyInjection/releases/tag/8.2.0).

**Comment by Thomas-X** [comment]
Great work! Thanks a bunch :)
